---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: dsvpn-centos-latest
    image: centos:latest
    pre_build_image: yes
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/playbook.yml
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: true
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: centos-latest
