---
#
# Ansible managed
#
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    # - namespace="archlinux" image="base"
    - image="debian" tag="unstable"
    - image="debian"
    - image="fedora"
    - image="fedora" tag="rawhide"
    - image="ubuntu"

matrix:
  allow_failures:
    - env: image="debian" tag="unstable"
    - env: image="fedora" tag="rawhide"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "RnWOZAlDIu1m8aINRaChUmdikgRzHplf3b35w5vWxsKJv7lIlK/nG1CSEkG+hK1YJXaco0/u4OsxYIteNVBwqM0xr63bZLwGnWzcP9g3q1ckL2Y0InXumHK+1/vBUFLvh5We3EGMln0OcHI+C0USmO52aerbHxxpUrxb0c9srEbHnkCWFfO4D6Ngn6dqKGU4mbef6TPe3INfATRe0zuYcTVYAH51ev2EHiRWJykWQZ/KbDmq66fGULvHv4vzvBbenFKr0Z3IBu2ZeRYCnGi1aEeiP99OjyLMrqH7SgSEZJZ1cUqXHE39FKOMnD0f2wszluI2fFedmf4Dd6F6ACmAUa4RBOzNfui/aQEAmohr4fFKZByTi/Li8Ne6AEst49LDzMvB3mwUpKQk/fYaXSzwcRLhyINnCxVyFnl9TJ4a5kDxwrDIVUR2yeKNUUr+yTARGIia6hxyHdSnyeqhO0yrAEcueiFy6xgwYoXQvZrZT25ngguXi/yV2E9uGxez4PA/QSRY5A5ZLQN8zHWo5j8Hk4+S4tPoI9K+sYG628A3atUBQRe61u8+dyqxNbhZEhJheJeWBv33PQaridp8qp43uDdyQNpInnO4eJQyfnJTCS8VQ37NLOe13+QQvnaSx6f07UN5aflSY3K9Fhqqlr4W1W2UabIZi5QBxXXiEn2HpDs="
  email: false
