---
# tasks file for dsvpn
- name: install requirements
  package:
    name: "{{ dsvpn_requirements }}"
    state: present
  register: dsvpn_install_requirements
  until: dsvpn_install_requirements is succeeded
  retries: 3

- name: unarchive
  unarchive:
    src: "{{ dsvpn_release_url }}"
    dest: "{{ dsvpn_temporary_directory }}"
    remote_src: yes
  register: dsvpn_unarchive
  until: dsvpn_unarchive is succeeded
  retries: 3

- name: make
  make:
    chdir: "{{ dsvpn_temporary_directory }}/dsvpn-{{ dsvpn_version }}"

- name: generate key
  command: dd if=/dev/urandom of={{ dsvpn_key_directory }}/vpn.key count=1 bs=32
  args:
    creates: "{{ dsvpn_key_directory }}/vpn.key"
  delegate_to: localhost

- name: copy key
  copy:
    src: "{{ dsvpn_key_directory }}/vpn.key"
    dest: "{{ dsvpn_key_directory }}/vpn.key"

- name: load tun module
  modprobe:
    name: tun
    state: present

- name: create /dev/net directory
  file:
    path: /dev/net
    state: directory

- name: create character device /dev/net/tun
  command: mknod /dev/net/tun c 10 200
  args:
    creates: /dev/net/tun

- name: start server
  command: ./dsvpn server {{ dsvpn_key_directory }}/vpn.key
  args:
    creates: nothing
    chdir: "{{ dsvpn_temporary_directory }}/dsvpn-{{ dsvpn_version }}"
  when:
    - ansible_virtualization_type != "docker"

- name: start client
  command: ./dsvpn client /tmp/vpn.key 34.216.127.34
  args:
    creates: nothing
    chdir: "{{ dsvpn_temporary_directory }}/dsvpn-{{ dsvpn_version }}"
  when:
    - ansible_virtualization_type != "docker"
