---
# tasks file for dsvpn

- name: import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install requirements
  ansible.builtin.package:
    name: "{{ dsvpn_requirements }}"
    state: present

- name: unarchive
  ansible.builtin.unarchive:
    src: "{{ dsvpn_release_url }}"
    dest: "{{ dsvpn_temporary_directory }}"
    remote_src: yes
    creates: "{{ dsvpn_temporary_directory }}/dsvpn-{{ dsvpn_version }}"
    mode: "0755"

- name: make
  community.general.make:
    chdir: "{{ dsvpn_temporary_directory }}/dsvpn-{{ dsvpn_version }}"

- name: install
  ansible.builtin.copy:
    src: "{{ dsvpn_temporary_directory }}/dsvpn-{{ dsvpn_version }}/dsvpn"
    dest: "{{ dsvpn_install_directory }}/dsvpn"
    remote_src: yes
    mode: "750"

- name: generate key
  ansible.builtin.command:
    cmd: dd if=/dev/urandom of={{ dsvpn_key_directory }}/vpn.key count=1 bs=32
    creates: "{{ dsvpn_key_directory }}/vpn.key"
  delegate_to: localhost

- name: set permissions on key
  ansible.builtin.file:
    path: "{{ dsvpn_key_directory }}/vpn.key"
    mode: "644"
  delegate_to: localhost

- name: copy key
  ansible.builtin.copy:
    src: "{{ dsvpn_key_directory }}/vpn.key"
    dest: "{{ dsvpn_key_directory }}/vpn.key"
    mode: "640"
    owner: root
    group: root
  notify:
    - restart dsvpn-server
    - restart dsvpn-client

- name: load tun module
  community.general.modprobe:
    name: tun
    state: present
  when:
    - ansible_connection not in [ "container", "docker", "community.docker.docker" ]

- name: create /dev/net directory
  ansible.builtin.file:
    path: /dev/net
    state: directory
    mode: "0755"

- name: create character device /dev/net/tun
  ansible.builtin.command:
    cmd: mknod /dev/net/tun c 10 200
    creates: /dev/net/tun

- name: create server
  ansible.builtin.include_tasks:
    file: server.yml
  when:
    - dsvpn_role == "server"

- name: create client
  ansible.builtin.include_tasks:
    file: client.yml
  when:
    - dsvpn_role == "client"
