---
# tasks file for dsvpn
- name: install requirements
  package:
    name: "{{ dsvpn_requirements }}"
    state: present
  register: dsvpn_install_requirements
  until: dsvpn_install_requirements is succeeded
  retries: 3

- name: unarchive
  unarchive:
    src: "{{ dsvpn_release_url }}"
    dest: "{{ dsvpn_temporary_directory }}"
    remote_src: yes
  register: dsvpn_unarchive
  until: dsvpn_unarchive is succeeded
  retries: 3

- name: make
  make:
    chdir: "{{ dsvpn_temporary_directory }}/dsvpn-{{ dsvpn_version }}"

- name: generate key
  command: dd if=/dev/urandom of={{ dsvpn_key_directory }}/vpn.key count=1 bs=32
  args:
    creates: "{{ dsvpn_key_directory }}/vpn.key"
  delegate_to: localhost

- name: copy key
  copy:
    src: "{{ dsvpn_key_directory }}/vpn.key"
    dest: "{{ dsvpn_key_directory }}/vpn.key"
  notify:
    - restart dsvpn server
    - restart dsvpn client

- name: load tun module
  modprobe:
    name: tun
    state: present
  when:
    - ansible_virtualization_type != "docker"

- name: create /dev/net directory
  file:
    path: /dev/net
    state: directory

- name: create character device /dev/net/tun
  command: mknod /dev/net/tun c 10 200
  args:
    creates: /dev/net/tun

- name: create server service
  import_role:
    name: robertdebock.service
  vars:
    service_list:
      - name: "dsvpn server"
        description: "Dead simple VPN server"
        start_command: "{{ dsvpn_temporary_directory }}/dsvpn-{{ dsvpn_version }}/dsvpn server {{ dsvpn_key_directory }}/vpn.key"
  when:
    - dsvpn_role: server
  notify:
    - systemctl daemon-reload
    - restart dsvpn server

- name: create client service
  import_role:
    name: robertdebock.service
  vars:
    service_list:
      - name: "dsvpn client"
        description: "Dead simple VPN client"
        start_command: "{{ dsvpn_temporary_directory }}/dsvpn-{{ dsvpn_version }}/dsvpn client {{ dsvpn_key_directory }}/vpn.key {{ dsvpn_server }}"
  when:
    - dsvpn_role: client
  notify:
    - systemctl daemon-reload
    - restart dsvpn client
