---
#
# Ansible managed
#

name: Ansible Molecule

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '7 4 4 * *'

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: ansible-lint
        uses: ansible-community/ansible-lint-action@main
  test:
    needs:
      - lint
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "enterpriselinux"
            tag: "latest"
          - image: "debian"
            tag: "latest"
          - image: "debian"
            tag: "bullseye"
          - image: "fedora"
            tag: "39"
          - image: "fedora"
            tag: "latest"
          - image: "fedora"
            tag: "rawhide"
          - image: "ubuntu"
            tag: "latest"
          - image: "ubuntu"
            tag: "jammy"
          - image: "ubuntu"
            tag: "focal"
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: molecule
        run: molecule converge
        env:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
